### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by LaineZ** [macsmac/modexplorer#3]
Просто падает с ошибкой
```
Ставлю зависимости
'npm' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:611
    throw err;
    ^

Error: Command failed: npm i
'npm' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:568:13)
    at Object.execSync (child_process.js:608:13)
    at Object.<anonymous> (D:\модники для майна\src\setup.js:8:27)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
Press any key to continue . . .
```

**Comment by necros2k7** [comment]
+1

**Comment by AltPlus30** [comment]
То же самое. Но что-то мне подсказывает, что автор уже этим не занимается.

**Comment by LaineZ** [comment]
очень жаль
